package main.java.com.article.dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

public abstract class DaoBase {

	/**
	 * returns the connection for the database.
	 * @return
	 * @throws ClassNotFoundException 
	 * @throws SQLException
	 */
	protected abstract Connection getConnection() throws ClassNotFoundException, SQLException ;
	
	/**
	 * Creates the table in the provided database;
	 * @throws SQLException
	 */
	public abstract void createArticlesTable() throws SQLException;
	
	/**
	 * Insert records into a table
	 * @param sql
	 * @throws SQLException
	 */
	public abstract void insertArticles(String sql) throws SQLException;
	
	/**
	 * returns the ResultSet which generated by executing a sql statement.
	 * @param tableName
	 * @param columns
	 * @param keys
	 * @throws SQLException
	 */
	public abstract ResultSet select(String tableName, List<String> columns, Map<String, Object> keys) throws SQLException;
}
